---
#dongtai-logstash服务
apiVersion: v1
kind: Service
metadata:
  name: dongtai-logstash-svc
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  ports:
    - name: agent-http
      port: 8082
      targetPort: 8082
      protocol: TCP
    - name: log-http
      port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    app: {{ template "dongtai.fullname" . }}-logstash